/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Coin_1: THREE.Mesh;
    Coin_2: THREE.Mesh;
    Coin_Star_1: THREE.Mesh;
    Coin_Star_2: THREE.Mesh;
    Diamond: THREE.Mesh;
  };
  materials: never;
};

export function CoinPenny(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Models.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Coin" position={[-1.332, 0, 20]}>
        <mesh
          name="Coin_1"
          castShadow
          receiveShadow
          geometry={nodes.Coin_1.geometry}
          material={nodes.Coin_1.material}
        />
        <mesh
          name="Coin_2"
          castShadow
          receiveShadow
          geometry={nodes.Coin_2.geometry}
          material={nodes.Coin_2.material}
        />
      </group>
    </group>
  );
}

export function CoinNickel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Models.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Coin_Star" position={[0, 0, 20]}>
        <mesh
          name="Coin_Star_1"
          castShadow
          receiveShadow
          geometry={nodes.Coin_Star_1.geometry}
          material={nodes.Coin_Star_1.material}
        />
        <mesh
          name="Coin_Star_2"
          castShadow
          receiveShadow
          geometry={nodes.Coin_Star_2.geometry}
          material={nodes.Coin_Star_2.material}
        />
      </group>
    </group>
  );
}

export function CoinQuarter(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Models.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Diamond"
        castShadow
        receiveShadow
        geometry={nodes.Diamond.geometry}
        material={nodes.Diamond.material}
        position={[1.49, 0, 20]}
      />
    </group>
  );
}

useGLTF.preload("/Models.glb");
