/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame, useThree } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Curve: THREE.Mesh;
    Curve001: THREE.Mesh;
  };
  materials: never;
};

export function Logo(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/AquatopiaLogo.glb") as GLTFResult;
  const groupRef = useRef<THREE.Group>(null);
  const { pointer } = useThree();

  // Track mouse position and smoothly rotate the logo
  useFrame(() => {
    if (!groupRef.current) return;

    // Calculate tilt based on mouse position (-1 to 1 range)
    const targetRotationX = Math.PI / 2 - pointer.y * 0.2; // Base rotation + tilt
    const targetRotationY = -pointer.x * 0.02;
    const targetRotationZ = -pointer.x * 0.1;

    // Smooth interpolation
    groupRef.current.rotation.x = THREE.MathUtils.lerp(
      groupRef.current.rotation.x,
      targetRotationX,
      0.1,
    );
    groupRef.current.rotation.y = THREE.MathUtils.lerp(
      groupRef.current.rotation.y,
      targetRotationY,
      0.1,
    );
    groupRef.current.rotation.z = THREE.MathUtils.lerp(
      groupRef.current.rotation.z,
      targetRotationZ,
      0.1,
    );
  });

  return (
    <group
      ref={groupRef}
      {...props}
      dispose={null}
      scale={8}
      rotation={[Math.PI / 2, 0, 0]}
    >
      <mesh castShadow receiveShadow geometry={nodes.Curve.geometry}>
        <meshPhongMaterial
          color="#0A6BB4"
          specular="#ffffff"
          shininess={100}
          reflectivity={0.5}
        />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.Curve001.geometry}>
        <meshPhongMaterial
          color="#49D1F1"
          // specular="#4fc3f7"
          specular="#ffffff"
          shininess={80}
          reflectivity={0.3}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/AquatopiaLogo.glb");
