/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { AnimatedWaterRippleMaterial } from "@/components/waterSurfaceMaterial";

type GLTFResult = GLTF & {
  nodes: {
    Tank_Medium_1: THREE.Mesh;
    Tank_Medium_2: THREE.Mesh;
    Tank_Medium_3: THREE.Mesh;
    Tank_Medium_4: THREE.Mesh;
    Tank_Medium_5: THREE.Mesh;
    Tank_Medium_6: THREE.Mesh;
    Tank_Large_1: THREE.Mesh;
    Tank_Large_2: THREE.Mesh;
    Tank_Large_3: THREE.Mesh;
    Tank_Large_4: THREE.Mesh;
    Tank_Large_5: THREE.Mesh;
    Tank_Large_6: THREE.Mesh;
    Tank_Huge_1: THREE.Mesh;
    Tank_Huge_2: THREE.Mesh;
    Tank_Huge_3: THREE.Mesh;
    Tank_Huge_4: THREE.Mesh;
    Tank_Huge_5: THREE.Mesh;
    Tank_Huge_6: THREE.Mesh;
  };
  materials: never;
};

// Frame Material
const frameMaterial = new THREE.MeshToonMaterial({
  color: new THREE.Color(0x103d5f), // Navy color for the frame
});

// Glass Face Material
const glassFaceMaterial = new THREE.MeshBasicMaterial({
  color: new THREE.Color(0x516b9f), // White color for the glass face
  transparent: true,
  opacity: 0.7,
});

// Sand Material
const sandMaterial = new THREE.MeshToonMaterial({
  color: new THREE.Color(0xedc9af), // Light brown color for the sand
});

// FrameInner Material
const frameInnerMaterial = new THREE.MeshToonMaterial({
  color: new THREE.Color(0x596b82),
});

// Glass Corners Material
const glassCornersMaterial = new THREE.MeshToonMaterial({
  color: new THREE.Color(0xffffff), // White color for the glass corners
});

export function TankMedium(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/Models.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        receiveShadow
        geometry={nodes.Tank_Medium_1.geometry}
        material={glassCornersMaterial}
      />
      <mesh geometry={nodes.Tank_Medium_2.geometry} material={frameMaterial} />
      <mesh
        receiveShadow
        geometry={nodes.Tank_Medium_3.geometry}
        material={glassFaceMaterial}
      />
      <mesh
        receiveShadow
        geometry={nodes.Tank_Medium_4.geometry}
        material={sandMaterial}
      />
      <mesh
        receiveShadow
        geometry={nodes.Tank_Medium_5.geometry}
        material={frameInnerMaterial}
      />
      <mesh geometry={nodes.Tank_Medium_6.geometry}>
        <AnimatedWaterRippleMaterial
          uLineThickness={0.8}
          uRippleFrequency={4.0}
        />
      </mesh>
    </group>
  );
}

export function TankLarge(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/Models.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        receiveShadow
        geometry={nodes.Tank_Large_1.geometry}
        material={glassCornersMaterial}
      />
      <mesh geometry={nodes.Tank_Large_2.geometry} material={frameMaterial} />
      <mesh
        receiveShadow
        geometry={nodes.Tank_Large_3.geometry}
        material={glassFaceMaterial}
      />
      <mesh
        receiveShadow
        geometry={nodes.Tank_Large_4.geometry}
        material={sandMaterial}
      />
      <mesh
        receiveShadow
        geometry={nodes.Tank_Large_5.geometry}
        material={frameInnerMaterial}
      />
      <mesh geometry={nodes.Tank_Large_6.geometry}>
        <AnimatedWaterRippleMaterial />
      </mesh>
    </group>
  );
}

export function TankHuge(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/Models.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        receiveShadow
        geometry={nodes.Tank_Huge_1.geometry}
        material={glassCornersMaterial}
      />
      <mesh geometry={nodes.Tank_Huge_2.geometry} material={frameMaterial} />
      <mesh
        receiveShadow
        geometry={nodes.Tank_Huge_3.geometry}
        material={glassFaceMaterial}
      />
      <mesh
        receiveShadow
        geometry={nodes.Tank_Huge_4.geometry}
        material={sandMaterial}
      />
      <mesh
        receiveShadow
        geometry={nodes.Tank_Huge_5.geometry}
        material={frameInnerMaterial}
      />
      <mesh geometry={nodes.Tank_Huge_6.geometry}>
        <AnimatedWaterRippleMaterial />
      </mesh>
    </group>
  );
}

useGLTF.preload("/Models.glb");
